[package]
name = "pogodoro"
version = "0.1.0"
authors = ["joshcbrown <joshcarlbrown@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
crossterm = "0.25.0"
notify-rust = "4.7.0"
tui = "0.19.0"
unicode-width = "0.1.10"
